name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SUDO_PASSWORD: ${{ secrets.EC2_SUDO_PASSWORD }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USER}@${EC2_HOST} <<EOF
            cd test_django
            git pull origin main
            source venv/bin/activate
            python manage.py migrate
            echo '${EC2_SUDO_PASSWORD}' | sudo -S systemctl restart gunicorn
            echo '${EC2_SUDO_PASSWORD}' | sudo -S systemctl restart nginx
          EOF
          rm -r key.pem